SmsGateway.create(:carrier => "Alltel", :address => "message.alltel.com")
SmsGateway.create(:carrier => "AT&T", :address => "txt.att.net")
SmsGateway.create(:carrier => "Boost Mobile", :address => "myboostmobile.com")
SmsGateway.create(:carrier => "Cricket Wireless", :address => "sms.mycricket.com")
SmsGateway.create(:carrier => "Nextel", :address => "messaging.nextel.com")
SmsGateway.create(:carrier => "Sprint", :address => "messaging.sprintpcs.com")
SmsGateway.create(:carrier => "T-Mobile", :address => "message.alltel.com")
SmsGateway.create(:carrier => "Verizon", :address => "vtext.com")
SmsGateway.create(:carrier => "Virgin Mobile USA", :address => "vmobl.com")
SmsGateway.create(:carrier => "Bell Canada", :address => "txt.bellmobility.ca")
SmsGateway.create(:carrier => "Centennial Wireless", :address => "cwemail.com")
SmsGateway.create(:carrier => "Cellular South", :address => "csouth1.com")
SmsGateway.create(:carrier => "Cincinnati Bell", :address => "gocbw.com")
SmsGateway.create(:carrier => "Metro PCS", :address => "mymetropcs.com")
SmsGateway.create(:carrier => "Qwest", :address => "qwestmp.com")
SmsGateway.create(:carrier => "Rogers", :address => "pcs.rogers.com")
SmsGateway.create(:carrier => "Suncom", :address => "tms.suncom.com")
SmsGateway.create(:carrier => "Telus", :address => "msg.telus.com")
SmsGateway.create(:carrier => "US Cellular", :address => "email.uscc.net")
